name: Lint

on: 
  push:
    branches:
      - master
      - develop
  pull_request: 
  merge_group:

concurrency:
  # Cancel previous runs of this workflow for the same branch
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Merge CI fixes from sagemath/sage
      run: |
        .ci/merge-fixes.sh
      env:
        GH_TOKEN: ${{ github.token }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: pip install tox pycodestyle relint

    - name: Code style check with pycodestyle
      run: tox -e pycodestyle-minimal

    - name: Code style check with relint
      run: tox -e relint -- src/sage/

    - name: Validate docstring markup as RST
      run: tox -e rst
